apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  namespace: elk-test
spec:
  storageClassName: elastic-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/home/ubuntu/elkdata"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-31-25-18.ap-south-1.compute.internal
