apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pvc
  namespace: elk-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: elastic-sc
  resources:
    requests:
      storage: 5Gi
